<?xml version="1.0"?>
<robot name="jaguar_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find jaguar_description)/urdf/wheel.urdf.xacro"/>
    <!--<xacro:include filename="$(find jaguar_description)/urdf/accessories/3D_camera.urdf.xacro"/> -->
    <xacro:include filename="$(find jaguar_description)/urdf/accessories/zed.urdf.xacro"/>

    <property name="M_PI" value="3.14159"/>

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.085"/>
    <xacro:property name="wheel_radius" value="0.13"/>

    <!-- Base Size -->
    <property name="distance_from_ground" value="0.09"/>
    <property name="wheel_base_offset" value="0.03"/>
    <property name="base_x_size" value="${0.615-2*wheel_base_offset}"/>
    <property name="base_y_size" value="${0.56-wheel_length}"/>
    <property name="base_z_size" value="${0.255-distance_from_ground}"/>

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="${base_x_size-2*wheel_radius+2*wheel_base_offset}"/>
    <xacro:property name="track" value="${base_y_size+wheel_length}"/>
    <xacro:property name="wheel_vertical_offset" value="${wheel_radius}"/>

    <!-- Laser Position -->
    <property name="laser_x" value="${base_x_size/2-0.0725}"/>
    <property name="laser_y" value="0"/>
    <property name="laser_z" value="${0.255+0.05}"/>

    <!-- Laser Size -->
    <property name="laser_x_size" value="0.065"/>
    <property name="laser_y_size" value="0.09"/>
    <property name="laser_z_size" value="0.1"/>

    <!-- Camera Position -->
    <property name="camera_x" value="${base_x_size/2}"/>
    <property name="camera_y" value="-0.045"/>
    <property name="camera_z" value="0.15"/>

    <!-- Camera Size -->
    <property name="camera_radius" value="${0.025/2}"/>
    <property name="camera_length" value="0.01"/>

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${2*distance_from_ground}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.8"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${2*distance_from_ground}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
        <inertial>
            <mass value="33.455"/>
            <origin xyz="-0.08748 -0.00085 0.09947"/>
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296"/>
        </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="inertial_link"/>
    </joint>

    <!-- IMU exact position is unnecessary thus placed at the center of the platform.-->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 ${base_z_size}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <!-- Jaguar wheel macros -->
    <xacro:jaguar_wheel wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    </xacro:jaguar_wheel>
    <xacro:jaguar_wheel wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    </xacro:jaguar_wheel>
    <xacro:jaguar_wheel wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    </xacro:jaguar_wheel>
    <xacro:jaguar_wheel wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    </xacro:jaguar_wheel>

    <!-- Laser -->
    <joint name="laser_joint" type="fixed">
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <link name="laser_link">
        <!-- Removing the laser visual and collision properties
        because they affect the simulated pointcloud -->
        <!--<visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${laser_x_size} ${laser_y_size} ${laser_z_size}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 255 0.8"/>
            </material>
        </visual>-->
        <!--<collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${laser_x_size} ${laser_y_size} ${laser_z_size}"/>
            </geometry>
        </collision>-->
    </link>

    <!-- Camera -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="webcamera_link"/>
    </joint>

    <link name="webcamera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>
            <geometry>
                <cylinder length="${camera_length}" radius="${camera_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="255 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>
            <geometry>
                <cylinder length="${camera_length}" radius="${camera_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="depth_camera_pole_joint" type="fixed">
        <origin xyz="0 0 0.38" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="depth_camera_pole_link"/>
    </joint>

    <link name="depth_camera_pole_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.2625" radius="0.015"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.2625" radius="0.015"/>
            </geometry>
        </collision>
    </link>

    <!-- GPS exact position is unnecessary thus placed at the center of the platform. -->
    <joint name="gps_joint" type="fixed">
        <origin xyz="0 0 ${base_z_size}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="gps_link"/>
    </joint>

    <link name="gps_link"/>

    <xacro:if value="$(arg 3D_enabled)">

      <joint name="camera_frame_joint" type="fixed">
        <origin xyz="0 0 0.525" rpy="0 0 0 "/>
        <parent link="base_link"/>
        <child link="camera_link"/>
      </joint>

      <xacro:depth_camera prefix="camera"/>
    </xacro:if>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>

    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>50.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>odom/perfect</topicName>
        <gaussianNoise>0.0</gaussianNoise>
        <frameName>world</frameName>
        <xyzOffsets>0 0 0</xyzOffsets>
        <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>

    <plugin name="jaguar_imu_sensor" filename="libhector_gazebo_ros_imu.so">
        <updateRate>50.0</updateRate>
        <bodyName>base_link</bodyName>
        <frameId>base_link</frameId>
        <topicName>imu/data</topicName>
        <accelDrift>0.0 0.0 0.0</accelDrift>
        <accelGaussianNoise>0.0 0.0 0.0</accelGaussianNoise>
        <rateDrift>0.0 0.0 0.0</rateDrift>
        <rateGaussianNoise>0.0 0.0 0.0</rateGaussianNoise>
    </plugin>

    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>/</robotNamespace>
      <updateRate>40</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>49.9</referenceLatitude>
      <referenceLongitude>8.9</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>

</robot>
