
sensor_processor/type: stereo
sensor_processor/p_1:   0.03287
sensor_processor/p_2:   0 #-0.0001276
sensor_processor/p_3:   0.4850
sensor_processor/p_4:   200 #399.1046 
sensor_processor/p_5:   0 #0.000006735
sensor_processor/lateral_factor: 0.00137691
sensor_processor/depth_to_disparity_factor: 35 #47.3

