# Traversability map filter parameters
traversability_map_filters:
  - name: surfaceNormalsFilter
    type: gridMapFilters/NormalVectorsFilter
    params:
      estimation_radius: 0.05
      input_layer: elevation
      surface_normal_positive_axis: "z"
      output_layers_prefix: surface_normal_
      radius: 0.05
      normal_vector_positive_axis: z
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 0.13
  - name: stepFilter
    type: traversabilityFilters/StepFilter
    params:
      map_type: traversability_step
      critical_value: 0.136
      first_window_radius: 0.25
      second_window_radius: 0.25
      critical_cell_number: 4
  - name: roughnessFilter
    type: traversabilityFilters/RoughnessFilter
    params:
      map_type: traversability_roughness
      critical_value: 0.05
      estimation_radius: 0.10
# - name: minFilter
#   type: gridMapFilters/MinFilter
#   params:
#    layers: [traversability_slope, traversability_step, traversability_roughness]
#    layer_out: traversability
# - name: lowerThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    lower_threshold: 0.2
#    set_to: 0.0
#    layers: [traversability]
# - name: upperThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    upper_threshold: 0.9
#    set_to: 1.0
#    layers: [traversability]
  - name: math_expression
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: 1 -0.5 *(traversability_slope / 0.13) - 0.25 * (traversability_roughness / 0.05) - 0.25 * (traversability_step / 0.136)
    # expression: abs(elevation - elevation_smooth) # Surface roughness.
    # expression: 0.5 * (1.0 - (slope / 0.6)) + 0.5 * (1.0 - (roughness / 0.1))
#  - name: deletionFilter
#    type: gridMapFilters/DeletionFilter
#    params:
#      layers: [surface_normal_x, surface_normal_y, surface_normal_z]
