submap_service: "/elevation_mapping/get_submap"
map_frame_id: "/base_link"
robot_frame_id: "/odom"
min_update_rate: 0.2
map_center_x: 0.0
map_center_y: 0.0
map_length_x: 6.0
map_length_y: 6.0
footprint_yaw: 0.1
max_gap_width: 0.136
