odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: false

frequency: 50

odom0: jaguar_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true,  true,  true,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: false
odom0_differential: true

odom1: zed/odom
odom1_config: [true,  true, false,
               false, false, true,
               true,  true,  true,
               false, false, false,
               false, false, false]
odom1_queue_size: 10
odom2_nodelay: false
odom1_differential: true

odom2: odometry/gps
odom2_config: [true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom2_queue_size: 10
odom2_nodelay: false
odom2_differential: true

imu0: imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
imu0_queue_size: 10
imu0_nodelay: false
imu0_differential: false
imu0_remove_gravitational_acceleration: true

