point_cloud_topic: /camera/depth/points # "/pointcloud_sampler/pointcloud" #"zed/point_cloud/cloud_registered"
map_frame_id: "/base_link"
robot_base_frame_id: "/base_link"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 1 #200
track_point_frame_id: "/base_link"
sensor_frame_id: "/camera_link"
min_update_rate: 5.0
relocate_rate: 4.0
fused_map_publishing_rate: 2.0
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
#####
length_in_x: 6.5
length_in_y: 6.5
position_x: 0.0
position_y: 0.0
resolution: 0.2 # at 0.06 for better analysis & at 0.2 to visualize traversability
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
#surface_normal_estimation_radius: 0.015
#surface_normal_positive_axis: z
enable_visibility_cleanup: true
visibility_cleanup_rate: 1.5

# https://github.com/ethz-asl/elevation_mapping/issues/33
# This fixes the latency problem with elevation mapping!
# (catkin build elevation_mapping -DCMAKE_BUILD_TYPE=Release)