point_cloud_topic: "/zed/point_cloud/cloud_registered" #/camera/depth/points # "/pointcloud_sampler/pointcloud" #"/zed/point_cloud/cloud_registered"
map_frame_id: "/base_link"
robot_base_frame_id: "/base_link"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "/base_link"
sensor_frame_id: "/camera_link"
min_update_rate: 5.0
relocate_rate: 10.0
fused_map_publishing_rate: 8.0
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
length_in_x: 5.0
length_in_y: 5.0
position_x: 0.0
position_y: 0.0
resolution: 0.04 # at 0.06 for better analysis & at 0.2 to visualize traversability
# Setting a very high max_variance allows the elevation mapping procedure
# to generate elevation map even for values further away (with lower certainty)
min_variance: 0.000009
max_variance: 1000
# The combination of really low mahalanobis_distance_threshold
# and very high multi_height_noise forces the elevation_mapping
# to overwrite previous elevation data instead of smoothing them.
# This works very well on simulation, but it needs to be tested
# on real hardware extensively
mahalanobis_distance_threshold: 0.01
multi_height_noise: 100.0
#surface_normal_estimation_radius: 0.015
#surface_normal_positive_axis: z
enable_visibility_cleanup: true
visibility_cleanup_rate: 1.5
sensor_cutoff_min_depth: 0.3
sensor_cutoff_max_depth: 4.5

# https://github.com/ethz-asl/elevation_mapping/issues/33
# This fixes the latency problem with elevation mapping!
# (catkin build elevation_mapping -DCMAKE_BUILD_TYPE=Release)
