# The rate in Hz at which to run the control loop and send velocity commands to the base.
controller_frequency: 30.0 # Default
# How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
planner_patience: 5.0 # Default
# How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
controller_patience: 15.0 # Default
# The distance away from the robot in meters at which obstacles will be cleared from the costmap when attempting to clear space in the map.
conservative_reset_dist: 3.5 # Default
# Whether or not to enable the move_base recovery behaviors to attempt to clear out space.
recovery_behavior_enabled: true # Default
# Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space.
clearing_rotation_allowed: true # Default
# Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state.
shutdown_costmaps: false # Default
# How long in seconds to allow for oscillation before executing recovery behaviors.
oscillation_timeout: 0.0 # Default
# How far in meters the robot must move to be considered not to be oscillating.
oscillation_distance: 0.5 # Default
# The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, the global planner will only run when a new goal is received or the local planner reports that its path is blocked.
planner_frequency: 0.2 # Default
